### ISSUE TITLE
TypeError: join() argument must be str or bytes, not 'NoneType'

### ISSUE THREAD

**Issue by bemoregt** [amaggi/waveloc#108]
Hi, @amaggi @nlanget 

I have met this error. 
--------------------------------------------------------------
kerbal@kraken ~/waveloc/examples $ python3 setup_examples.py 
Traceback (most recent call last):
  File "setup_examples.py", line 12, in <module>
    test_data_dir = os.path.join(base_path, 'test_data', 'raw_data')
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
kerbal@kraken ~/waveloc/examples $ 
-----------------------------------------------------------------------------

What's wrong with me ?
There are few install information. )-:

**Comment by ThomasLecocq** [comment]
Hi,

You have to set up the ``WAVELOC_PATH`` environment variable.
Not doing so results in 
```python
base_path = os.getenv('WAVELOC_PATH')
```
being ``None`` and failing.

**Comment by LandAndLand** [comment]
> 嗨，
> 
> 您必须设置`WAVELOC_PATH`环境变量。
> 不这样做会导致
> 
> ```python
> base_path = os.getenv（' WAVELOC_PATH '）
> ```
> 
> 存在`None`和失败。



> 嗨，@ amaggi @nlanget
> 
> ## 我遇到了这个错误。
> ## kerbal @kraken~ / waveloc / examples $ python3 setup_examples.py 
> Traceback（最近一次调用最后一次）：
> 文件“setup_examples.py”，第12行，在
> test_data_dir = os.path.join（base_path，'test_data'，'raw_data'）
> 文件“/usr/lib/python3.5/posixpath.py”，第89行，加入
> genericpath._check_arg_types（'join'，a，* p）
> 文件“/usr/lib/python3.5/genericpath.py”，线143，在_check_arg_types 
> （funcname的，S。**类**。**名**来自无））
> 类型错误：join（）方法的参数必须是海峡或字节，而不是'NoneType' 
> 商店页面@海怪〜/ waveloc /例子$
> 我怎么了？
> 安装信息很少。） - ：

怎么样了，这个问题你解决了吗
